name: Deploy Summarizer AI

on:
  push:
    branches:
      - prod
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create CodeDeploy Deployment
        run: |
          APPLICATION_NAME="SummarizerAIApplication"
          DEPLOYMENT_GROUP_NAME="${GITHUB_REF##*/}" # Extracts 'prod' or 'staging'
          if [ "$DEPLOYMENT_GROUP_NAME" == "prod" ]; then
            DEPLOYMENT_GROUP_NAME="ProdDeploymentGroup" # Map 'prod' branch to Prod DG
          elif [ "$DEPLOYMENT_GROUP_NAME" == "staging" ]; then
            DEPLOYMENT_GROUP_NAME="StagingDeploymentGroup" # Map 'staging' branch to Staging DG
          fi

          aws deploy create-deployment \
            --application-name "$APPLICATION_NAME" \
            --deployment-group-name "$DEPLOYMENT_GROUP_NAME" \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --revision '{"revisionType": "GitHub", "gitHubLocation": {"repository": "${{ github.repository }}", "commitId": "${{ github.sha }}"}}' \
            --region "${{ secrets.AWS_REGION }}"